export enum DisputeReason {
  MISSION_NOT_COMPLETED = 'MISSION_NOT_COMPLETED',
  BAD_QUALITY = 'BAD_QUALITY',
  DELAY = 'DELAY',
  OVERCHARGE = 'OVERCHARGE',
  BEHAVIOR = 'BEHAVIOR',
  FRAUD = 'FRAUD',
  OTHER = 'OTHER',
}
