export enum DisputeStatus {
  OPEN = 'OPEN',
  WAITING_PROVIDER = 'WAITING_PROVIDER',
  WAITING_CLIENT = 'WAITING_CLIENT',
  UNDER_REVIEW = 'UNDER_REVIEW',
  DECIDED = 'DECIDED',
  APPEALED = 'APPEALED',
  CLOSED = 'CLOSED',
}
