import { simulatePricing1688, simulatePricingFromProduct } from '@/lib/pricing1688.refactored'
import { computeProductPricing } from '@/lib/logistics'

const assertEqual = (a: any, b: any, message?: string) => {
  if (a !== b) {
    console.error('ASSERTION FAILED:', message || '', { expected: b, actual: a })
    process.exitCode = 2
    throw new Error('Assertion failed')
  }
}

const runScenario = (label: string, product: any, input: any) => {
  console.log(`\n--- Scenario: ${label}`)
  const pricingSummary = computeProductPricing(product)
  const sim = simulatePricingFromProduct(product, input)

  console.log('computeProductPricing.fees:', pricingSummary.fees)
  console.log('simulation:', sim.breakdown)

  if (!pricingSummary.fees) {
    console.error('No fees generated by computeProductPricing — expected fees for imported product')
    process.exit(3)
  }

  // Compare service fee and insurance
  const serviceFromSummary = pricingSummary.fees!.serviceFeeAmount
  const insuranceFromSummary = pricingSummary.fees!.insuranceAmount

  const serviceFromSim = sim.breakdown.serviceFee
  const insuranceFromSim = sim.breakdown.insuranceFee

  assertEqual(serviceFromSummary, serviceFromSim, 'service fee mismatch')
  assertEqual(insuranceFromSummary, insuranceFromSim, 'insurance fee mismatch')

  console.log('OK: fees match')
}

const main = () => {
  try {
    // Small order
    runScenario('small', {
      price1688: 20, // ¥
      baseCost: undefined,
      exchangeRate: 100,
      serviceFeeRate: 10,
      insuranceRate: 2.5,
      weightKg: 1
    }, { shippingMethod: 'air_15', weightKg: 1 })

    // Medium order
    runScenario('medium', {
      price1688: 100,
      baseCost: undefined,
      exchangeRate: 100,
      serviceFeeRate: 10,
      insuranceRate: 2.5,
      weightKg: 5
    }, { shippingMethod: 'air_express', weightKg: 5 })

    // Bulk order (quantity affects margin, not fees)
    runScenario('bulk', {
      price1688: 100,
      baseCost: undefined,
      exchangeRate: 100,
      serviceFeeRate: 10,
      insuranceRate: 2.5,
      weightKg: 10
    }, { shippingMethod: 'sea_freight', volumeM3: 1, orderQuantity: 60 })

    console.log('\nAll pricing tests passed')
  } catch (err) {
    console.error('Pricing tests failed:', err)
    process.exit(1)
  }
}

main()
